require "json"
require "fileutils"
NOOP = !(ARGV[1])
CONFIG_PATH = ARGV[0] || "./backup_config.json"
CONFIG = JSON.parse(File.read(CONFIG_PATH))
START_TIME = Time.now.strftime("%Y-%m-%d_%H-%M-%S")
COCKPIT_USERNAME = CONFIG["cockpitUsername"] || ""
ROOT_PATH = `pwd`.chomp
TITLE = CONFIG['title'] || ""
BACKUP_PATH = File.join(ROOT_PATH,"#{TITLE}-#{START_TIME}")
USERNAME = CONFIG["username"]
TAR_COMMAND = "tar -czf #{BACKUP_PATH}.tar.gz -C #{File.dirname(BACKUP_PATH)} #{File.basename(BACKUP_PATH)}"
ARCHIVE_NAME = "#{BACKUP_PATH}.tar.gz".split("/").last
UNTAR_COMMAND = "tar -xzvf /home/#{USERNAME}/#{ARCHIVE_NAME}"
SECTIONS_SEPARATOR = "################################################"
H1_PREFIX = "########"

def gsubVars(string)
	return string.gsub("$BACKUP_PATH", BACKUP_PATH)
		.gsub("$COCKPIT_USERNAME", COCKPIT_USERNAME)
		.gsub("$START_TIME", START_TIME)
		.gsub("$ROOT_PATH", ROOT_PATH)
		.gsub("$USERNAME", USERNAME)
		.gsub("$TITLE", TITLE)
end
def gsubVarsRestore(string)
	return string.gsub("$BACKUP_PATH", '.')
		.gsub("$COCKPIT_USERNAME", COCKPIT_USERNAME)
		.gsub("$START_TIME", START_TIME)
		.gsub("$ROOT_PATH", ROOT_PATH)
		.gsub("$USERNAME", USERNAME)
		.gsub("$TITLE", TITLE)
end
def doBackupCommandsAndPrepareRestoreCommands(confHash = {})
	puts SECTIONS_SEPARATOR
	puts "#{H1_PREFIX} Backing up files"
	puts "#{H1_PREFIX} (NOOP MODE IS ON, NO FILES COPYING)" if NOOP
	puts SECTIONS_SEPARATOR
	preCommands = ["\n\n#{SECTIONS_SEPARATOR}", "#{H1_PREFIX} Stage 2: Setting up other pre-requisites"]
	restoreCommands = ["\n\n#{SECTIONS_SEPARATOR}","#{H1_PREFIX} Stage 3: Restoring backup files"]
	postCommands = ["\n\n#{SECTIONS_SEPARATOR}", "#{H1_PREFIX} Stage 4: Restarting and enabling services"]
	aptPrefix = "DEBIAN_FRONTEND=noninteractive apt update; apt upgrade; apt install -y"
	packages = []
	confHash["softwares"].each do |s|
		softwarePath = File.join(BACKUP_PATH, s['name'])
		FileUtils.mkdir_p(softwarePath, verbose: true, noop: NOOP)
		s['backup'].each do |e|
			if e['type'] == "FILE" then
				categoryPath = File.join(softwarePath, e['name'])
				FileUtils.mkdir_p(categoryPath, verbose: true, noop: NOOP)
				FileUtils.cp(gsubVars(e['path']),categoryPath , noop: NOOP ,verbose: true)
				command = "cp -v ./#{s['name']}/#{e['name']}/#{e['path'].split("/").last} #{e['path']}"
				restoreCommands.push("\n#### #{e['name']}")
				restoreCommands.push(command)
			elsif e["type"] == "DIR"
				pathUnlast = File.join(e['path'].split('/')[0..-1])
				FileUtils.cp_r(gsubVars(e['path']), softwarePath, verbose: true, noop: NOOP)
				command = "cp -vr ./#{s['name']}/#{e['path'].split("/").last}/* #{gsubVars(pathUnlast)}"
				restoreCommands.push("\n#### #{e['name']}")
				restoreCommands.push(command)
			elsif e["type"] == "COMMAND"
				puts "RUNNING COMMAND #{gsubVars(e['path'])}" if NOOP
				system(gsubVars(e['path'])) if !NOOP
			end
		end
		preCommands.concat(preparePrePostCommands(s['preRestore']))
		postCommands.concat(preparePrePostCommands(s['postRestore']))
		packages.concat(s['packages'])
	end
	puts "\n\n#{SECTIONS_SEPARATOR}"
	puts "#{H1_PREFIX} BACKING UP FINISHED"
	puts "#{SECTIONS_SEPARATOR}\n"
	preCommands.unshift("#!/bin/bash",
		"set -x",
		SECTIONS_SEPARATOR,
		"#{H1_PREFIX} This is an autogenerated restore script",
		"#{H1_PREFIX} Be sure it is being run as ROOT",
		SECTIONS_SEPARATOR,
		"#{H1_PREFIX} Stage1: Installing ubuntu packages",
		"#{aptPrefix} #{packages.join(" ")}"
	)
	preCommands.push(SECTIONS_SEPARATOR)
	restoreCommands.push(SECTIONS_SEPARATOR)
	postCommands.push("#{SECTIONS_SEPARATOR}\n\n")
	if !NOOP
		puts "#{H1_PREFIX} Saving backup/restore script and config"
		FileUtils.cp(CONFIG_PATH, BACKUP_PATH,verbose: true)
		FileUtils.cp(__FILE__, BACKUP_PATH,verbose: true)
		File.open(File.join(BACKUP_PATH, 'restore.sh'), "w") do |file|
			file.puts preCommands.join("\n")
			file.puts restoreCommands.join("\n")
			file.puts postCommands.join("\n")
		end
		puts "#{H1_PREFIX} Archiving the backup"
		system(TAR_COMMAND)
	else
		puts "\n\n\n#{SECTIONS_SEPARATOR}"
		puts "#{H1_PREFIX} RESTORE SCRIPT BELOW"
		puts "#{SECTIONS_SEPARATOR}\n\n"
		puts preCommands
		puts restoreCommands
		puts postCommands
	end
	output = [
		"\n\n#{SECTIONS_SEPARATOR}",
		"#{H1_PREFIX} All needed files were archived",
		"#### scp command: to copy file FROM this server: ",
		"scp #{TITLE}:#{BACKUP_PATH}.tar.gz ~/Desktop",
		"#{SECTIONS_SEPARATOR}",
		"#{H1_PREFIX} Short restore manual",
		"#### scp command: to copy file to this server to restore:",
		"scp ~/Desktop/#{ARCHIVE_NAME} #{TITLE}:/home/ubuntu/\n",
		"#### untar command:",
		UNTAR_COMMAND,
		"\n#### run restore script:",
		"cd /home/ubuntu/#{TITLE}-#{START_TIME}/; sudo bash ./restore.sh\n",
		"#{SECTIONS_SEPARATOR}\n"
	]
	puts output.join("\n")
end
def preparePrePostCommands(preRestoreArray = [])
	return preRestoreArray.map { |e| "\n#### #{e["name"]}\n#{gsubVarsRestore(e["command"])}" }
end
doBackupCommandsAndPrepareRestoreCommands(CONFIG)
