#!/usr/bin/ruby
require "json"
require "fileutils"
require "erb"
require 'optparse'
require 'ostruct'

# Structure to hold configuration settings
options = OpenStruct.new(
	conf:    './backup_config.json',
	op:      false,  
	verbose: false,
)
opt_parser = OptionParser.new do |opts|
	opts.banner = "Usage: backup_script.rb --conf PATH -v"
	opts.on("--conf PATH", "Path to config file. (Default: ./backup_config.json)") do |path|
    options.conf = path
  end
	opts.on("--[no-]op", "Enable operation mode. Use --no-op to dry-run. (Default: false)") do |o|
    	options.op = o
	end

	opts.on("-v", "--verbose", "Enable verbose output. (Default: false)") do
	options.verbose = true
	end
	opts.on("-h", "--help", "Prints this help message.") do
		puts opts
		exit
	end
end
begin
	opt_parser.parse!(ARGV)
rescue OptionParser::InvalidOption => e
	puts e.message
	puts opt_parser
	exit(1)
end
VERBOSE = options.verbose
NOOP = !options.op
CONFIG_PATH = File.expand_path(options.conf)
CONFIG = JSON.parse(File.read(CONFIG_PATH))
START_TIME = Time.now.strftime("%Y-%m-%d_%H-%M-%S")
COCKPIT_USERNAME = CONFIG["cockpitUsername"] || ""
ROOT_PATH = File.expand_path(`pwd`.chomp)
TITLE = CONFIG['title'] || ""
BACKUP_PATH = File.join(ROOT_PATH,"#{TITLE}-#{START_TIME}")
USERNAME = CONFIG["username"]
TAR_COMMAND = "tar -czf #{BACKUP_PATH}.tar.gz -C #{File.dirname(BACKUP_PATH)} #{File.basename(BACKUP_PATH)}"
ARCHIVE_NAME = "#{BACKUP_PATH}.tar.gz".split("/").last
UNTAR_COMMAND = "tar -xzvf /home/#{USERNAME}/#{ARCHIVE_NAME}"
SECTIONS_SEPARATOR = "################################################"
H1_PREFIX = "########"
puts "#{H1_PREFIX} ENTER A PASSWORD FOR COCKPIT_USER:"
COCKPIT_USER_PASSWORD = gets.chomp
RESTORE_SH_ERB = "#!/bin/bash
set -x
<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> This is an autogenerated restore script built on <%=CONFIG_PATH%> config
<%=H1_PREFIX%> Be sure it is being run as ROOT



<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage1: Installing custom repos and packages
DEBIAN_FRONTEND=noninteractive apt update; apt upgrade
<%=@customAptRepoCommands.join('; ')%> 
apt install -y <%=@aptPackages.join(' ')%> 
<%=SECTIONS_SEPARATOR%>


<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage 2: Setting up other pre-requisites <%=@preCommands.join('')%>
<%=SECTIONS_SEPARATOR%>

<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage 3: Restoring backup files <%=@restoreCommands.join('')%>
<%=SECTIONS_SEPARATOR%>


<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage 4: Restarting and enabling services <%=@postCommands.join('')%>
<%=SECTIONS_SEPARATOR%>"

def gsubVars(string)
	return string.gsub("$BACKUP_PATH", BACKUP_PATH)
		.gsub("$COCKPIT_USERNAME", COCKPIT_USERNAME)
		.gsub("$COCKPIT_USER_PASSWORD", COCKPIT_USER_PASSWORD)
		.gsub("$START_TIME", START_TIME)
		.gsub("$ROOT_PATH", ROOT_PATH)
		.gsub("$USERNAME", USERNAME)
		.gsub("$TITLE", TITLE)
end
def gsubVarsRestore(string)
	return string.gsub("$BACKUP_PATH", '.')
		.gsub("$COCKPIT_USERNAME", COCKPIT_USERNAME)
		.gsub("$COCKPIT_USER_PASSWORD", COCKPIT_USER_PASSWORD)
		.gsub("$START_TIME", START_TIME)
		.gsub("$ROOT_PATH", ROOT_PATH)
		.gsub("$USERNAME", USERNAME)
		.gsub("$TITLE", TITLE)
		
end
def doBackupCommandsAndPrepareRestoreCommands(confHash = {})
	puts SECTIONS_SEPARATOR
	puts "#{H1_PREFIX} Backing up files"
	puts "#{H1_PREFIX} (NOOP MODE IS ON, NO FILES COPYING)" if NOOP
	puts SECTIONS_SEPARATOR
	@preCommands = []
	@restoreCommands = []
	@postCommands = []
	@customAptRepoCommands = []
	@aptPackages = []
	confHash["softwares"].each do |s|
		softwarePath = File.join(BACKUP_PATH, s['name'])
		FileUtils.mkdir_p(softwarePath, verbose: true, noop: NOOP)
		s['backup'].each do |e|
			if e['type'] == "FILE" then
				categoryPath = File.join(softwarePath, e['name'])
				FileUtils.mkdir_p(categoryPath, verbose: true, noop: NOOP)
				FileUtils.cp(gsubVars(e['path']),categoryPath , noop: NOOP ,verbose: true)
				command = "cp -v ./#{s['name']}/#{e['name']}/#{e['path'].split("/").last} #{e['path']}"
				@restoreCommands.push("\n#### #{e['name']}\n")
				@restoreCommands.push(command)
			elsif e["type"] == "DIR"
				pathUnlast = File.join(e['path'].split('/')[0..-1])
				FileUtils.cp_r(gsubVars(e['path']), softwarePath, verbose: true, noop: NOOP)
				command = "cp -vr ./#{s['name']}/#{e['path'].split("/").last}/* #{gsubVars(pathUnlast)}"
				@restoreCommands.push("\n#### #{e['name']}\n")
				@restoreCommands.push(command)
			elsif e["type"] == "COMMAND"
				puts "RUNNING COMMAND #{gsubVars(e['path'])}" if NOOP
				system(gsubVars(e['path'])) if !NOOP
			end
		end
		@preCommands.concat(preparePrePostCommands(s['preRestore']))
		@postCommands.concat(preparePrePostCommands(s['postRestore']))
		@customAptRepoCommands.concat(s['customAptRepoCommands']) if s['customAptRepoCommands']
		@aptPackages.concat(s['aptPackages'])
	end
	puts "\n\n#{SECTIONS_SEPARATOR}"
	puts "#{H1_PREFIX} BACKING UP FINISHED"
	puts "#{SECTIONS_SEPARATOR}\n"
	content = ERB.new(RESTORE_SH_ERB)
	if !NOOP	
		puts "#{H1_PREFIX} Saving backup/restore script and config"
		FileUtils.cp(CONFIG_PATH, BACKUP_PATH,verbose: true)
		FileUtils.cp(__FILE__, BACKUP_PATH,verbose: true)
		File.open(File.join(BACKUP_PATH, 'restore.sh'), "w") do |file|
			file.puts(content.result(binding))
		end
		puts "#{H1_PREFIX} Archiving the backup"
		system(TAR_COMMAND)
	else
		puts "\n\n\n#{SECTIONS_SEPARATOR}"
		puts "#{H1_PREFIX} RESTORE SCRIPT BELOW"
		puts "#{SECTIONS_SEPARATOR}\n\n"
		puts content.result(binding)
	end
	output = [
		"\n\n#{SECTIONS_SEPARATOR}",
		"#{H1_PREFIX} All needed files were archived",
		"#### scp command: to copy file FROM this server: ",
		"scp #{TITLE}:#{BACKUP_PATH}.tar.gz ~/Desktop",
		"#{SECTIONS_SEPARATOR}",
		"#{H1_PREFIX} Short restore manual",
		"#### scp command: to copy file to this server to restore:",
		"scp ~/Desktop/#{ARCHIVE_NAME} #{TITLE}:/home/ubuntu/\n",
		"#### untar command:",
		UNTAR_COMMAND,
		"\n#### run restore script:",
		"cd /home/ubuntu/#{TITLE}-#{START_TIME}/; sudo bash ./restore.sh\n",
		"#{SECTIONS_SEPARATOR}\n"
	]
	puts output.join("\n")
end
def preparePrePostCommands(preRestoreArray = [])
	return preRestoreArray.map { |e| "\n#### #{e["name"]}\n#{gsubVarsRestore(e["command"])}" }
end
doBackupCommandsAndPrepareRestoreCommands(CONFIG)
