#!/usr/bin/ruby
require "json"
require "fileutils"
require "erb"
require 'optparse'
require 'ostruct'

# Structure to hold configuration settings
options = OpenStruct.new(
	conf: nil,
	op: false,
	verbose: false,
	cockpitUsername: nil,
	username: nil,
	combineMegazord: [],
	name: nil
)

opt_parser = OptionParser.new do |opts|
	opts.banner = "
	Usage: sudo COCKPIT_PASSWORD='somepassword' ruby backup.rb --conf ./.template_config.json -v --no-op
           sudo COCKPIT_PASSWORD='somepassword' ruby backup.rb --combine-megazord '3-nginx.json,4-letsencrypt.json,9-cloudconnexa.json,7-mongodb.json' --name 'vpsId.countryCode.example.com' --username ubuntu --cockpit-username NONE --op -v
           sudo ruby backup.rb --help
	"
	opts.on("-c PATH", "--conf PATH", "Path to config file. (Default: ./softwares/1-network.json)") do |path|
    	options.conf = path
	end
	opts.on("-n SERVERNAME", "--name SERVERNAME", "Server Name, sent via this param has highest priority. Second Priority is CONFIG['title']. 'vpsId.coutryCode.example.com' if empty in both places") do |path|
    	options.name = path
	end
	opts.on("-c STRING", "--cockpit-username STRING", "Username for a cockpit user, sent via this param has highest priority. Second Priority is CONFIG['cockpitUsername'], 'cockpit' if empty in both places") do |p|
    	options.cockpitUsername = p
	end
	opts.on("-u STRING", "--username STRING", "Username for a ssh user, sent via this param has highest priority. Second Priority is CONFIG['username'], 'ubuntu' if empty in both places") do |p|
    	options.username = p
	end
	opts.on("-o", "--[no-]op", "Enable (--op) or disable (--no-op) actual files copying. (Default: --no-op)") do |o|
    	options.op = o
	end
	opts.on("-v", "--verbose", "Enable verbose output for files copying. (Default: false)") do
		options.verbose = true
	end
	opts.on("--combine-megazord SOFTWARES", "Enable JSON combining from softwares list, use comma separated file names from ./softwares/ folder, f.e.: --combine-megazord '1-network.json,3-nginx.json'. (Default: '1-network.json' if --conf not passed also)") do |s|
		options.combineMegazord = s.split(',').sort if !s.nil?
	end
	opts.on("-h", "--help", "Prints this help message.") do
		puts opts
		exit
	end
end
begin
	opt_parser.parse!(ARGV)
rescue OptionParser::InvalidOption => e
	puts e.message
	puts opt_parser
	exit(1)
end
options.combineMegazord = ['1-network.json'] if options.combineMegazord.empty? & options.conf.nil?
# Layout related constants. Keep first symbol '#' to be sure restore.sh does not get some text uncommented
H2_PREFIX = "###"
H1_PREFIX = "#{H2_PREFIX} #{'--'*3}"
SECTIONS_SEPARATOR = "#{H2_PREFIX}#{'===' * 30}"

VERBOSE = options.verbose
NOOP = !options.op
START_TIME = Time.now.strftime("%Y-%m-%d_%H-%M-%S")
ROOT_PATH = File.expand_path(`pwd`.chomp)
if options.combineMegazord.empty?
	config = JSON.parse(File.read(File.expand_path(options.conf)))
	config_file_path = [File.expand_path(options.conf)]
else
	megazord = []
	options.combineMegazord.map { |e| megazord.push(content = JSON.parse(File.read(File.expand_path("./softwares/#{e}")))) } 
	config = {'softwares' => megazord}
	config_file_path = options.combineMegazord.map { |e| "./softwares/#{e}" }
end
CONFIG_PATH = config_file_path
# CONST assigned depending on priority Command-Line-Params -> JSON Config -> Local Defaults
TITLE = options['name'] || config['title'] || "vpsId.countryCode.example.com"
BACKUP_PATH = File.join(ROOT_PATH,"#{TITLE}-#{START_TIME}")
COCKPIT_USERNAME = options.cockpitUsername || config["cockpitUsername"] || abort("Error: No Cockpit Username provided in config or CLI params!")
COCKPIT_USER_PASSWORD = ENV['COCKPIT_PASSWORD'] || config["cockpitUserPassword"] || abort("Error: No Cockpit Password provided in config or COCKPIT_PASSWORD env var")
USERNAME = options.username || config["username"] || "ubuntu"

CONFIG = { #Resulting Config with all Constants
	"title" => TITLE,
	"megazordCombined?" => !options.combineMegazord.empty?,
	"username" => USERNAME,
	"cockpitUsername" => COCKPIT_USERNAME,
	"cockpitUserPassword" => COCKPIT_USER_PASSWORD,
	"softwares" => config["softwares"]
}
if VERBOSE then
	TAR_PREFIX = "tar -czvf"
else
	TAR_PREFIX = "tar -czf"
end


TAR_COMMAND = "#{TAR_PREFIX} #{BACKUP_PATH}.tar.gz -C #{File.dirname(BACKUP_PATH)} #{File.basename(BACKUP_PATH)}"
ARCHIVE_NAME = "#{BACKUP_PATH}.tar.gz".split("/").last
UNTAR_COMMAND = "tar -xzvf /home/#{USERNAME}/#{ARCHIVE_NAME}"


RESTORE_SH_ERB = "#!/bin/bash
set -x
<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> This is an autogenerated restore script built on <%=CONFIG_PATH%> config
<%=H1_PREFIX%> Be sure it is being run as ROOT
<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage1: Installing custom repos and packages
DEBIAN_FRONTEND=noninteractive apt update -y; apt upgrade -y
<%=@customAptRepoCommands.join('\n')%> 
apt install -y <%=@aptPackages.join(' ')%> 
<%=SECTIONS_SEPARATOR%>

<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage 2: Setting up other pre-requisites <%=@preCommands.join('')%>
<%=SECTIONS_SEPARATOR%>

<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage 3: Restoring backup files <%=@restoreCommands.join('')%>
<%=SECTIONS_SEPARATOR%>

<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> Stage 4: Restarting and enabling services <%=@postCommands.join('')%>
<%=SECTIONS_SEPARATOR%>

<%=SECTIONS_SEPARATOR%>
<%=H1_PREFIX%> !!! END OF RESTORE SCRIPT
<%=SECTIONS_SEPARATOR%>
"

HEADING = [
	SECTIONS_SEPARATOR,
	"#{H1_PREFIX} Backing up files",
	"#{H1_PREFIX} Script Configuration:",
	"#{H1_PREFIX}   * Combine Megazord Mode: #{!options.combineMegazord.empty?}",
	"#{H1_PREFIX}   * Config File(s) path: #{config_file_path}",
	"#{H1_PREFIX}   * Operational mode: #{!NOOP}",
	"#{H1_PREFIX}   * Verbose output: #{VERBOSE}",
	"#{H1_PREFIX}   * Backup root folder: #{BACKUP_PATH}",
	SECTIONS_SEPARATOR,
	"#{H1_PREFIX} Backup Configuration: ",
	"#{H1_PREFIX}   * Server Name: #{TITLE}",
	"#{H1_PREFIX}   * Softwares: #{CONFIG['softwares'].map { |e| e['name'] }}",
	"#{H1_PREFIX}   * SSH User: #{USERNAME}",
	"#{H1_PREFIX}   * Cockpit User: #{COCKPIT_USERNAME}",
	"#{H1_PREFIX}   * Cockpit User Password: #{COCKPIT_USER_PASSWORD}",
	SECTIONS_SEPARATOR,
	"#{H1_PREFIX} BACKING UP STARTED",
	SECTIONS_SEPARATOR
]
FOOTER = [
	"\n\n#{SECTIONS_SEPARATOR}",
	"#{H1_PREFIX} All needed files were archived. See below for hints on how to copy backup and restore it",
	"#{H2_PREFIX} scp command: to copy file FROM this server: ",
	"scp #{TITLE}:#{BACKUP_PATH}.tar.gz ~/Desktop",
	"#{SECTIONS_SEPARATOR}",
	"",
	"#{H1_PREFIX} To Retore:",
	"#{H2_PREFIX} copy file to this server",
	"scp ~/Desktop/#{ARCHIVE_NAME} #{TITLE}:/home/ubuntu/",
	"#{H2_PREFIX} untar command:",
	UNTAR_COMMAND,
	"#{H2_PREFIX} run restore script",
	"cd /home/ubuntu/#{TITLE}-#{START_TIME}/; sudo bash ./restore.sh",
	"#{SECTIONS_SEPARATOR}\n"
]
def gsubVarsGeneric(string)
	return string.gsub("$COCKPIT_USERNAME", COCKPIT_USERNAME)
		.gsub("$COCKPIT_USER_PASSWORD", COCKPIT_USER_PASSWORD)
		.gsub("$START_TIME", START_TIME)
		.gsub("$ROOT_PATH", ROOT_PATH)
		.gsub("$USERNAME", USERNAME)
		.gsub("$TITLE", TITLE)
end
def gsubVars(string)
	return gsubVarsGeneric(string).gsub("$BACKUP_PATH", BACKUP_PATH)
		
end
def gsubVarsRestore(string)
	return gsubVarsGeneric(string).gsub("$BACKUP_PATH", '.')
end
def doBackupCommandsAndPrepareRestoreCommands(confHash = {})
	puts HEADING.join("\n")
	@preCommands = []
	@restoreCommands = []
	@postCommands = []
	@customAptRepoCommands = []
	@aptPackages = []
	confHash["softwares"].each do |s|
		softwarePath = File.join(BACKUP_PATH, s['name'])
		FileUtils.mkdir_p(softwarePath, verbose: (VERBOSE || NOOP), noop: NOOP)
		s['backup'].each do |e|
			if e['type'] == "FILE" then
				categoryPath = File.join(softwarePath, e['name'])
				FileUtils.mkdir_p(categoryPath, verbose: (VERBOSE || NOOP), noop: NOOP)
				FileUtils.cp(gsubVars(e['path']),categoryPath , noop: NOOP ,verbose: (VERBOSE || NOOP))
				command = "cp -v ./#{s['name']}/#{e['name']}/#{e['path'].split("/").last} #{e['path']}"
				@restoreCommands.push("\n#{H2_PREFIX} #{e['name']}\n")
				@restoreCommands.push(command)
			elsif e["type"] == "DIR"
				pathUnlast = File.join(e['path'].split('/')[0..-1])
				FileUtils.cp_r(gsubVars(e['path']), softwarePath, verbose: (VERBOSE || NOOP), noop: NOOP)
				command = "cp -vr ./#{s['name']}/#{e['path'].split("/").last}/* #{gsubVars(pathUnlast)}"
				@restoreCommands.push("\n#{H2_PREFIX} #{e['name']}\n")
				@restoreCommands.push(command)
			elsif e["type"] == "COMMAND"
				puts gsubVars(e['path']) if NOOP
				if !NOOP
					command = gsubVars(e['path'])
  					if !system(command)
    					abort("\nError: Command failed to execute!\nCommand: #{command}\nExit Code: #{$?.exitstatus}")
  					end
				end
			end
		end
		@preCommands.concat(preparePrePostCommands(s['preRestore']))
		@postCommands.concat(preparePrePostCommands(s['postRestore']))
		@customAptRepoCommands.concat(s['customAptRepoCommands']) if s['customAptRepoCommands']
		@aptPackages.concat(s['aptPackages'])
	end
	puts "#{SECTIONS_SEPARATOR}"
	puts "#{H1_PREFIX} BACKING UP FINISHED"
	puts "#{H1_PREFIX} ACTUAL FILES COPYING WAS SKIPPED AS NOOP MODE ENABLED" if NOOP
	puts "#{SECTIONS_SEPARATOR}"
	content = ERB.new(RESTORE_SH_ERB).result(binding)
	if NOOP	
		puts "\n#{SECTIONS_SEPARATOR}"
		filepath = File.join(ROOT_PATH,"#{TITLE}.autogenerated.json")
		puts "#{H1_PREFIX} Saving JSON Config into #{filepath}"
		File.write(filepath, JSON.pretty_generate(CONFIG))
		puts "#{H1_PREFIX} RESTORE SCRIPT BELOW"
		puts "#{SECTIONS_SEPARATOR}\n\n"
		puts content
	else
		puts "#{H1_PREFIX} Saving backup/restore script and config"
		puts "#{H2_PREFIX} Saving backup.rb"
		File.write(File.join(BACKUP_PATH,'backup.rb'), File.read(__FILE__))
		puts "#{H2_PREFIX} Saving restore.sh"
		File.write(File.join(BACKUP_PATH,'restore.sh'), content)
		puts "#{H2_PREFIX} Saving #{TITLE}.json"
		File.write(File.join(BACKUP_PATH,"#{TITLE}.json"), JSON.pretty_generate(CONFIG))
		puts "#{H1_PREFIX} Archiving the backup"
		puts "#{H2_PREFIX} #{TAR_COMMAND}"
		if !system(TAR_COMMAND)
			abort("Error: Failed to create archive. Command exited with #{$?}")
		end
		puts "#{SECTIONS_SEPARATOR}"
	end
	puts FOOTER.join("\n")
end
def preparePrePostCommands(preRestoreArray = [])
	return preRestoreArray.map { |e| "\n#{H2_PREFIX} #{e["name"]}\n#{gsubVarsRestore(e["command"])}" }
end
doBackupCommandsAndPrepareRestoreCommands(CONFIG)
